services:
  gateway:
    build: ./gateway
    ports:
      - "5001:5001"
    networks:
      - app_network

  model_api:
    build: ./model_api
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
